name: Tmate SSH Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "50 */5 * * *"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests colorama websockets==10.4
          pip install numpy scikit-learn xgboost catboost lightgbm scipy prettytable tensorflow
        
        
      - name: Start tmate session
        run: tmate -F
        
